import QtQuick 2.15

// Login screen. Only core QtQuick is used so it loads in both the Qt5 and Qt6 greeters
// (QtQuick.Controls is not available in the Qt5 one). Colours, font and corner radius come
// from theme.conf, generated by scripts/theme-switch.
Item {
    id: root
    width: 1920
    height: 1080

    readonly property string uiFont: config.font
    readonly property string iconFont: config.iconFont
    readonly property int radius: parseInt(config.radius)
    property int sessionIndex: sessionModel.lastIndex
    property string userName: userModel.lastUser

    Image {
        anchors.fill: parent
        source: config.background
        fillMode: Image.PreserveAspectCrop
    }
    Rectangle { anchors.fill: parent; color: config.tint }

    Column {
        id: content
        anchors.centerIn: parent
        anchors.verticalCenterOffset: -40
        spacing: 6
        opacity: 0
        Component.onCompleted: { fadeIn.start(); password.forceActiveFocus() }
        NumberAnimation { id: fadeIn; target: content; property: "opacity"; to: 1; duration: 700; easing.type: Easing.OutQuint }

        Text {
            id: date
            anchors.horizontalCenter: parent.horizontalCenter
            color: config.subtext
            font.family: root.uiFont
            font.pixelSize: 18
            font.weight: Font.Medium
            text: Qt.formatDate(new Date(), "dddd, d MMMM")
        }
        Text {
            id: clock
            anchors.horizontalCenter: parent.horizontalCenter
            color: config.text
            font.family: root.uiFont
            font.pixelSize: 124
            font.weight: Font.Thin
            text: Qt.formatTime(new Date(), "HH:mm")
        }
        Item { width: 1; height: 14 }

        // Password field
        Rectangle {
            id: field
            anchors.horizontalCenter: parent.horizontalCenter
            width: 300
            height: 46
            radius: root.radius
            color: config.surfaceA
            border.width: 2
            border.color: password.activeFocus ? config.accent : config.edge
            Behavior on border.color { ColorAnimation { duration: 250 } }

            TextInput {
                id: password
                anchors.fill: parent
                anchors.leftMargin: 16
                anchors.rightMargin: 16
                echoMode: TextInput.Password
                passwordCharacter: "●"
                horizontalAlignment: TextInput.AlignHCenter
                verticalAlignment: TextInput.AlignVCenter
                color: config.text
                font.family: root.uiFont
                font.pixelSize: 16
                clip: true
                focus: true
                onAccepted: if (text.length > 0) sddm.login(root.userName, text, root.sessionIndex)
            }

            Text {
                anchors.centerIn: parent
                visible: password.text.length === 0
                text: "Enter password"
                color: config.subtext
                opacity: 0.7
                font.family: root.uiFont
                font.pixelSize: 15
            }

            SequentialAnimation {
                id: shake
                PropertyAnimation { target: field; property: "x"; to: field.x - 10; duration: 50 }
                PropertyAnimation { target: field; property: "x"; to: field.x + 10; duration: 80 }
                PropertyAnimation { target: field; property: "x"; to: field.x - 6;  duration: 70 }
                PropertyAnimation { target: field; property: "x"; to: field.x;      duration: 60 }
            }
        }

        Text {
            anchors.horizontalCenter: parent.horizontalCenter
            color: config.subtext
            font.family: root.uiFont
            font.pixelSize: 13
            font.weight: Font.Medium
            text: root.userName.length ? root.userName : "Welcome"
        }
        Text {
            id: error
            anchors.horizontalCenter: parent.horizontalCenter
            color: config.red
            font.family: root.uiFont
            font.pixelSize: 13
            text: ""
            opacity: text.length ? 1 : 0
            Behavior on opacity { NumberAnimation { duration: 200 } }
        }
    }

    Connections {
        target: sddm
        function onLoginFailed() {
            error.text = "Incorrect password"
            password.text = ""
            shake.start()
            password.forceActiveFocus()
        }
        function onLoginSucceeded() { error.text = "" }
    }

    // Session picker (bottom-left): click to cycle through the available sessions.
    Rectangle {
        id: sessionButton
        anchors.left: parent.left
        anchors.bottom: parent.bottom
        anchors.margins: 28
        width: sessionLabel.implicitWidth + 32
        height: 34
        radius: root.radius
        color: sessionArea.containsMouse ? config.edge : config.surfaceB
        Behavior on color { ColorAnimation { duration: 150 } }

        Repeater {
            id: sessionNames
            model: sessionModel
            delegate: Item {
                visible: index === root.sessionIndex
                Component.onCompleted: if (visible) sessionLabel.text = model.name
                onVisibleChanged: if (visible) sessionLabel.text = model.name
            }
        }
        Text {
            id: sessionLabel
            anchors.centerIn: parent
            color: config.subtext
            font.family: root.uiFont
            font.pixelSize: 13
        }
        MouseArea {
            id: sessionArea
            anchors.fill: parent
            hoverEnabled: true
            enabled: sessionNames.count > 1
            onClicked: root.sessionIndex = (root.sessionIndex + 1) % sessionNames.count
        }
    }

    // Power buttons (bottom-right)
    Row {
        anchors.right: parent.right
        anchors.bottom: parent.bottom
        anchors.margins: 28
        spacing: 10

        Repeater {
            model: [
                { glyph: "", can: sddm.canSuspend,  act: function() { sddm.suspend() } },
                { glyph: "", can: sddm.canReboot,   act: function() { sddm.reboot() } },
                { glyph: "", can: sddm.canPowerOff, act: function() { sddm.powerOff() } }
            ]
            delegate: Rectangle {
                width: 38; height: 38
                visible: modelData.can
                radius: Math.min(root.radius, 19)
                color: hover.containsMouse ? config.edge : config.surfaceB
                Behavior on color { ColorAnimation { duration: 150 } }
                Text {
                    anchors.centerIn: parent
                    text: modelData.glyph
                    color: hover.containsMouse ? config.accent : config.subtext
                    font.family: root.iconFont
                    font.pixelSize: 15
                }
                MouseArea { id: hover; anchors.fill: parent; hoverEnabled: true; onClicked: modelData.act() }
            }
        }
    }

    Timer {
        interval: 1000; running: true; repeat: true
        onTriggered: {
            clock.text = Qt.formatTime(new Date(), "HH:mm")
            date.text = Qt.formatDate(new Date(), "dddd, d MMMM")
        }
    }
}
