import QtQuick
import QtQuick.Controls

// Login screen. Colours, font and corner radius come from theme.conf (generated by
// scripts/theme-switch), so it matches the desktop theme it was installed with.
Item {
    id: root
    width: 1920
    height: 1080

    readonly property string uiFont: config.font
    readonly property string iconFont: config.iconFont
    readonly property int radius: parseInt(config.radius)
    property int sessionIndex: sessionModel.lastIndex
    property string userName: userModel.lastUser

    Image {
        anchors.fill: parent
        source: config.background
        fillMode: Image.PreserveAspectCrop
    }
    Rectangle { anchors.fill: parent; color: config.tint }

    Column {
        id: content
        anchors.centerIn: parent
        anchors.verticalCenterOffset: -40
        spacing: 6
        opacity: 0
        Component.onCompleted: { fadeIn.start(); password.forceActiveFocus() }
        NumberAnimation { id: fadeIn; target: content; property: "opacity"; to: 1; duration: 700; easing.type: Easing.OutQuint }

        Text {
            id: date
            anchors.horizontalCenter: parent.horizontalCenter
            color: config.subtext
            font.family: root.uiFont
            font.pixelSize: 18
            font.weight: Font.Medium
            text: Qt.formatDate(new Date(), "dddd, d MMMM")
        }
        Text {
            id: clock
            anchors.horizontalCenter: parent.horizontalCenter
            color: config.text
            font.family: root.uiFont
            font.pixelSize: 124
            font.weight: Font.Thin
            text: Qt.formatTime(new Date(), "HH:mm")
        }
        Item { width: 1; height: 14 }

        // Password field
        Rectangle {
            id: field
            anchors.horizontalCenter: parent.horizontalCenter
            width: 300
            height: 46
            radius: root.radius
            color: Qt.rgba(Qt.color(config.surface).r, Qt.color(config.surface).g, Qt.color(config.surface).b, 0.75)
            border.width: 2
            border.color: password.activeFocus ? config.accent : Qt.rgba(1, 1, 1, 0.12)
            Behavior on border.color { ColorAnimation { duration: 250 } }

            TextField {
                id: password
                anchors.fill: parent
                anchors.leftMargin: 16
                anchors.rightMargin: 16
                echoMode: TextInput.Password
                passwordCharacter: "●"
                horizontalAlignment: TextInput.AlignHCenter
                verticalAlignment: TextInput.AlignVCenter
                color: config.text
                font.family: root.uiFont
                font.pixelSize: 16
                background: Item {}
                onAccepted: if (text.length > 0) sddm.login(root.userName, text, root.sessionIndex)
            }

            Text {
                anchors.centerIn: parent
                visible: password.text.length === 0
                text: "Enter password"
                color: config.subtext
                opacity: 0.7
                font.family: root.uiFont
                font.pixelSize: 15
            }

            SequentialAnimation {
                id: shake
                PropertyAnimation { target: field; property: "x"; to: field.x - 10; duration: 50 }
                PropertyAnimation { target: field; property: "x"; to: field.x + 10; duration: 80 }
                PropertyAnimation { target: field; property: "x"; to: field.x - 6;  duration: 70 }
                PropertyAnimation { target: field; property: "x"; to: field.x;      duration: 60 }
            }
        }

        Text {
            id: hint
            anchors.horizontalCenter: parent.horizontalCenter
            color: config.subtext
            font.family: root.uiFont
            font.pixelSize: 13
            font.weight: Font.Medium
            text: root.userName.length ? root.userName : "Welcome"
        }
        Text {
            id: error
            anchors.horizontalCenter: parent.horizontalCenter
            color: config.red
            font.family: root.uiFont
            font.pixelSize: 13
            text: ""
            opacity: text.length ? 1 : 0
            Behavior on opacity { NumberAnimation { duration: 200 } }
        }
    }

    Connections {
        target: sddm
        function onLoginFailed() {
            error.text = "Incorrect password"
            password.text = ""
            shake.start()
            password.forceActiveFocus()
        }
        function onLoginSucceeded() { error.text = "" }
    }

    // Session picker (bottom-left) and power buttons (bottom-right)
    ComboBox {
        id: sessions
        anchors.left: parent.left
        anchors.bottom: parent.bottom
        anchors.margins: 28
        width: 190
        model: sessionModel
        textRole: "name"
        currentIndex: root.sessionIndex
        onActivated: root.sessionIndex = currentIndex
        font.family: root.uiFont
        font.pixelSize: 13
        contentItem: Text {
            leftPadding: 14
            text: sessions.displayText
            color: config.subtext
            font: sessions.font
            verticalAlignment: Text.AlignVCenter
        }
        background: Rectangle {
            radius: root.radius
            color: Qt.rgba(Qt.color(config.surface).r, Qt.color(config.surface).g, Qt.color(config.surface).b, 0.55)
        }
        indicator: Item {}
    }

    Row {
        anchors.right: parent.right
        anchors.bottom: parent.bottom
        anchors.margins: 28
        spacing: 10

        Repeater {
            model: [
                { glyph: "", tip: "Suspend",  can: sddm.canSuspend,  act: function() { sddm.suspend() } },
                { glyph: "", tip: "Restart",  can: sddm.canReboot,   act: function() { sddm.reboot() } },
                { glyph: "", tip: "Shut down", can: sddm.canPowerOff, act: function() { sddm.powerOff() } }
            ]
            delegate: Rectangle {
                width: 38; height: 38
                visible: modelData.can
                radius: Math.min(root.radius, 19)
                color: hover.containsMouse ? Qt.rgba(1, 1, 1, 0.14) : Qt.rgba(Qt.color(config.surface).r, Qt.color(config.surface).g, Qt.color(config.surface).b, 0.55)
                Behavior on color { ColorAnimation { duration: 150 } }
                Text {
                    anchors.centerIn: parent
                    text: modelData.glyph
                    color: hover.containsMouse ? config.accent : config.subtext
                    font.family: root.iconFont
                    font.pixelSize: 15
                }
                MouseArea { id: hover; anchors.fill: parent; hoverEnabled: true; onClicked: modelData.act() }
                ToolTip.visible: hover.containsMouse
                ToolTip.text: modelData.tip
                ToolTip.delay: 400
            }
        }
    }

    Timer {
        interval: 1000; running: true; repeat: true
        onTriggered: {
            clock.text = Qt.formatTime(new Date(), "HH:mm")
            date.text = Qt.formatDate(new Date(), "dddd, d MMMM")
        }
    }
}
