/* GENERATED by scripts/theme-switch ({{name}}) from templates/confirm/confirm.css.tpl. Do not edit. */
window.primo-confirm { background-color: #{{base}}; color: #{{text}}; }

.confirm-icon {
    background-color: rgba({{red_rgb}}, 0.16);
    color: #{{red}};
    border-radius: 999px;
    min-width: 46px;
    min-height: 46px;
    font-family: "{{font_icon}}";
    font-size: 20px;
}
.confirm-icon.info { background-color: rgba({{accent_rgb}}, 0.16); color: #{{accent}}; }

.confirm-title { font-weight: 700; font-size: 17px; color: #{{text}}; }
.confirm-text  { color: #{{subtext}}; font-size: 13px; }

button.confirm-btn {
    border: none;
    box-shadow: none;
    background-image: none;
    border-radius: {{rounding}}px;
    padding: 8px 18px;
    font-weight: 600;
    min-height: 0;
    transition: background-color 0.15s ease;
}
button.confirm-cancel { background-color: rgba({{text_rgb}}, 0.08); color: #{{text}}; }
button.confirm-cancel:hover { background-color: rgba({{text_rgb}}, 0.15); }
button.confirm-ok { background-color: #{{accent}}; color: #{{base}}; }
button.confirm-ok:hover { background-color: #{{accent2}}; }
button.confirm-ok.danger { background-color: #{{red}}; color: #{{base}}; }
button.confirm-ok.danger:hover { background-color: #{{orange}}; }
button.confirm-btn:focus-visible { outline: 2px solid rgba({{accent_rgb}}, 0.8); outline-offset: 2px; }
