/* GENERATED by scripts/theme-switch ({{name}}). Do not edit. Edit the theme, then re-apply it.
   Named colours understood by libadwaita (GTK4) and adw-gtk3 (GTK3). */
@define-color accent_color #{{accent}};
@define-color accent_bg_color #{{accent}};
@define-color accent_fg_color #{{base}};
@define-color destructive_color #{{red}};
@define-color destructive_bg_color #{{red}};
@define-color destructive_fg_color #{{base}};
@define-color success_color #{{green}};
@define-color success_bg_color #{{green}};
@define-color success_fg_color #{{base}};
@define-color warning_color #{{yellow}};
@define-color warning_bg_color #{{yellow}};
@define-color warning_fg_color #{{crust}};
@define-color error_color #{{red}};
@define-color error_bg_color #{{red}};
@define-color error_fg_color #{{base}};

@define-color window_bg_color #{{base}};
@define-color window_fg_color #{{text}};
@define-color view_bg_color #{{view}};
@define-color view_fg_color #{{text}};
@define-color headerbar_bg_color #{{mantle}};
@define-color headerbar_fg_color #{{text}};
@define-color headerbar_border_color #{{mantle}};
@define-color headerbar_backdrop_color #{{base}};
@define-color headerbar_shade_color rgba(0, 0, 0, 0.12);
@define-color headerbar_darker_shade_color rgba(0, 0, 0, 0.12);
@define-color card_bg_color #{{surface0}};
@define-color card_fg_color #{{text}};
@define-color card_shade_color rgba(0, 0, 0, 0.1);
@define-color dialog_bg_color #{{base}};
@define-color dialog_fg_color #{{text}};
@define-color popover_bg_color #{{surface0}};
@define-color popover_fg_color #{{text}};
@define-color popover_shade_color rgba(0, 0, 0, 0.1);
@define-color sidebar_bg_color #{{mantle}};
@define-color sidebar_fg_color #{{text}};
@define-color sidebar_backdrop_color #{{mantle}};
@define-color sidebar_border_color rgba({{text_rgb}}, 0.08);
@define-color sidebar_shade_color rgba(0, 0, 0, 0.1);
@define-color secondary_sidebar_bg_color #{{mantle}};
@define-color secondary_sidebar_fg_color #{{text}};
@define-color secondary_sidebar_backdrop_color #{{mantle}};
@define-color secondary_sidebar_border_color rgba({{text_rgb}}, 0.08);
@define-color secondary_sidebar_shade_color rgba(0, 0, 0, 0.1);
@define-color thumbnail_bg_color #{{surface1}};
@define-color thumbnail_fg_color #{{text}};
@define-color shade_color rgba(0, 0, 0, 0.1);
@define-color scrollbar_outline_color #{{base}};

/* Match the theme's shape: crisp themes get tighter corners, pill themes stay soft. */
button, entry, spinbutton, .card, popover > contents, menu, .osd { border-radius: {{rounding}}px; }
