# GENERATED by scripts/theme-switch ({{name}}). Do not edit.
[Settings]
gtk-theme-name={{gtk_theme}}
gtk-icon-theme-name={{icon_theme}}
gtk-cursor-theme-name={{cursor_theme}}
gtk-cursor-theme-size={{cursor_size}}
gtk-font-name={{font_sans}} 10
gtk-application-prefer-dark-theme={{prefer_dark}}
