# GENERATED by scripts/theme-switch ({{name}}). Do not edit.
[ColorEffects:Disabled]
Color={{surface1_rgb}}
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color={{overlay_rgb}}
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate={{surface1_rgb}}
BackgroundNormal={{surface0_rgb}}
DecorationFocus={{accent_rgb}}
DecorationHover={{accent_rgb}}
ForegroundActive={{accent_rgb}}
ForegroundInactive={{overlay_rgb}}
ForegroundLink={{accent_rgb}}
ForegroundNegative={{red_rgb}}
ForegroundNeutral={{orange_rgb}}
ForegroundNormal={{text_rgb}}
ForegroundPositive={{green_rgb}}
ForegroundVisited={{magenta_rgb}}

[Colors:Complementary]
BackgroundAlternate={{base_rgb}}
BackgroundNormal={{mantle_rgb}}
DecorationFocus={{accent_rgb}}
DecorationHover={{accent_rgb}}
ForegroundActive={{accent_rgb}}
ForegroundInactive={{overlay_rgb}}
ForegroundLink={{accent_rgb}}
ForegroundNegative={{red_rgb}}
ForegroundNeutral={{orange_rgb}}
ForegroundNormal={{text_rgb}}
ForegroundPositive={{green_rgb}}
ForegroundVisited={{magenta_rgb}}

[Colors:Header]
BackgroundAlternate={{base_rgb}}
BackgroundNormal={{mantle_rgb}}
DecorationFocus={{accent_rgb}}
DecorationHover={{accent_rgb}}
ForegroundActive={{accent_rgb}}
ForegroundInactive={{overlay_rgb}}
ForegroundLink={{accent_rgb}}
ForegroundNegative={{red_rgb}}
ForegroundNeutral={{orange_rgb}}
ForegroundNormal={{text_rgb}}
ForegroundPositive={{green_rgb}}
ForegroundVisited={{magenta_rgb}}

[Colors:Selection]
BackgroundAlternate={{accent_rgb}}
BackgroundNormal={{accent_rgb}}
DecorationFocus={{accent_rgb}}
DecorationHover={{accent_rgb}}
ForegroundActive={{base_rgb}}
ForegroundInactive={{base_rgb}}
ForegroundLink={{base_rgb}}
ForegroundNegative={{base_rgb}}
ForegroundNeutral={{base_rgb}}
ForegroundNormal={{base_rgb}}
ForegroundPositive={{base_rgb}}
ForegroundVisited={{base_rgb}}

[Colors:Tooltip]
BackgroundAlternate={{surface1_rgb}}
BackgroundNormal={{surface0_rgb}}
DecorationFocus={{accent_rgb}}
DecorationHover={{accent_rgb}}
ForegroundActive={{accent_rgb}}
ForegroundInactive={{overlay_rgb}}
ForegroundLink={{accent_rgb}}
ForegroundNegative={{red_rgb}}
ForegroundNeutral={{orange_rgb}}
ForegroundNormal={{text_rgb}}
ForegroundPositive={{green_rgb}}
ForegroundVisited={{magenta_rgb}}

[Colors:View]
BackgroundAlternate={{mantle_rgb}}
BackgroundNormal={{view_rgb}}
DecorationFocus={{accent_rgb}}
DecorationHover={{accent_rgb}}
ForegroundActive={{accent_rgb}}
ForegroundInactive={{overlay_rgb}}
ForegroundLink={{accent_rgb}}
ForegroundNegative={{red_rgb}}
ForegroundNeutral={{orange_rgb}}
ForegroundNormal={{text_rgb}}
ForegroundPositive={{green_rgb}}
ForegroundVisited={{magenta_rgb}}

[Colors:Window]
BackgroundAlternate={{mantle_rgb}}
BackgroundNormal={{base_rgb}}
DecorationFocus={{accent_rgb}}
DecorationHover={{accent_rgb}}
ForegroundActive={{accent_rgb}}
ForegroundInactive={{overlay_rgb}}
ForegroundLink={{accent_rgb}}
ForegroundNegative={{red_rgb}}
ForegroundNeutral={{orange_rgb}}
ForegroundNormal={{text_rgb}}
ForegroundPositive={{green_rgb}}
ForegroundVisited={{magenta_rgb}}

[General]
ColorScheme=Primo
Name=Primo ({{name}})
shadeSortColumn=true

[KDE]
contrast=4

[WM]
activeBackground={{mantle_rgb}}
activeBlend={{text_rgb}}
activeForeground={{text_rgb}}
inactiveBackground={{base_rgb}}
inactiveBlend={{overlay_rgb}}
inactiveForeground={{overlay_rgb}}
