# GENERATED by scripts/theme-switch ({{name}}). Do not edit.
$base    = rgba({{base}}ff)
$surface = rgba({{surface0}}cc)
$text    = rgba({{text}}ff)
$subtext = rgba({{subtext}}ff)
$accent  = rgba({{accent}}ff)
$red     = rgba({{red}}ff)
$yellow  = rgba({{yellow}}ff)
$font    = {{font_sans}}
$lock_brightness = {{lock_brightness}}
