# GENERATED by scripts/theme-switch ({{name}}). Do not edit.
$base    = rgba({{base}}ff)
$surface = rgba({{surface0}}b3)
$text    = rgba({{text}}ff)
$subtext = rgba({{text}}b3)
$accent  = rgba({{accent}}ff)
$accent2 = rgba({{accent2}}ff)
$red     = rgba({{red}}ff)
$yellow  = rgba({{yellow}}ff)
$font    = {{font_sans}}
$lock_brightness = {{lock_brightness}}
$tint = rgba({{base}}{{lock_tint}})
$lock_bg = {{lock_bg}}
$lock_blur = {{lock_blur}}
$input_rounding = {{input_rounding}}
