-- GENERATED by scripts/theme-switch ({{name}}). Do not edit.
return {
    name        = "{{name}}",
    border_size = {{border_size}},
    gaps_in     = {{gaps_in}},
    gaps_out    = {{gaps_out}},
    rounding    = {{rounding}},
    blur_size   = {{blur_size}},
    blur_passes = {{blur_passes}},
    colors = {
        active_border   = { "rgba({{accent}}ee)", "rgba({{accent2}}ee)" },
        inactive_border = "rgba({{overlay}}aa)",
        shadow          = "rgba({{crust}}ee)",
    },
}
