// GENERATED by scripts/theme-switch ({{name}}). Do not edit.
{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {
        "type": "data",
        "source": " $1▄██████▄    ▄██████▄▄\n$1██████████   ██████████\n$1██████████   ███████████\n$1██████████   ███████████\n$1██████████   ███████████\n$1██████████   ██████████\n$1██████████   ▀██████▀▀\n$1██████████\n$1██████████    $2▄▄▄▄▄\n$1██████████   $2███████\n$1██████████   $2███████\n $1▀██████▀    $2▀█████▀",
        "color": { "1": "38;2;{{logo_sgr}}", "2": "38;2;{{logo_accent_sgr}}" }, "padding": { "right": 3 }
    },
    "display": {
        "separator": "  ",
        "color": { "keys": "38;2;{{accent_sgr}}", "title": "38;2;{{accent2_sgr}}", "separator": "38;2;{{overlay_sgr}}" }
    },
    "modules": [
        "title",
        { "type": "os", "key": "os " },
        { "type": "kernel", "key": "ker" },
        { "type": "uptime", "key": "up " },
        { "type": "packages", "key": "pkg" },
        { "type": "wm", "key": "wm " },
        { "type": "terminal", "key": "trm" },
        { "type": "shell", "key": "sh " },
        { "type": "cpu", "key": "cpu" },
        { "type": "memory", "key": "mem" },
        "break",
        "colors"
    ]
}
