# GENERATED by scripts/theme-switch ({{name}}). Do not edit.
"$schema" = 'https://starship.rs/config-schema.json'

palette = "primo"
add_newline = false
command_timeout = 600

format = """
$username$hostname$directory$git_branch$git_status$python$nodejs$rust$golang$cmd_duration
$character"""

[palettes.primo]
text = "#{{text}}"
subtext = "#{{subtext}}"
overlay = "#{{overlay}}"
accent = "#{{accent}}"
accent2 = "#{{accent2}}"
red = "#{{red}}"
yellow = "#{{yellow}}"
green = "#{{green}}"

[character]
success_symbol = "[❯](bold accent)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[directory]
style = "bold accent"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "
read_only_style = "red"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "accent2"
format = "[$symbol$branch]($style) "

[git_status]
style = "yellow"
format = '([$all_status$ahead_behind]($style) )'
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
modified = "!"
staged = "+"
deleted = "✘"

[cmd_duration]
min_time = 2000
format = "[took $duration]($style) "
style = "subtext"

[username]
show_always = false
style_user = "subtext"
format = "[$user]($style)@"

[hostname]
ssh_only = true
style = "subtext"
format = "[$hostname]($style) "

[python]
symbol = " "
style = "yellow"
format = "[$symbol($version )]($style)"

[nodejs]
symbol = " "
style = "green"
format = "[$symbol($version )]($style)"

[rust]
symbol = " "
style = "red"
format = "[$symbol($version )]($style)"

[golang]
symbol = " "
style = "accent"
format = "[$symbol($version )]($style)"
