/* GENERATED by scripts/theme-switch ({{name}}) from templates/wofi/menu.css.tpl. Do not edit. */
* { font-family: "{{font_sans}}", "{{font_icon}}", "Adwaita Sans", sans-serif; }

window { margin: 0; background-color: transparent; font-size: 14px; }

#window {
    border-radius: {{menu_radius}}px;
    background-color: alpha(#{{base}}, 0.94);
    border: 1px solid alpha(#{{text}}, 0.12);
}

#outer-box { margin: 8px; background-color: transparent; border: none; }
#inner-box { margin: 0; background-color: transparent; border: none; }
#scroll { margin: 0; border: none; }
#input { margin: 0; padding: 0; border: none; background: transparent; min-height: 0; }

#entry { padding: 9px 10px; margin: 2px 0; border: none; border-radius: {{rounding}}px; }
#text { margin: 0 6px; color: #{{text}}; }
#entry:selected {
    background-color: alpha(#{{accent}}, 0.28);
}
#entry:selected #text { color: #{{text}}; font-weight: bold; }
