/* GENERATED by scripts/theme-switch ({{name}}) from templates/wofi/style.css.tpl. Do not edit. */
* {
    font-family: "{{font_sans}}", "{{font_icon}}", "Adwaita Sans", sans-serif;
}

window {
    margin: 0;
    background-color: transparent;
    font-size: 15px;
}

#window {
    border-radius: {{menu_radius}}px;
    background-color: alpha(#{{base}}, 0.95);
    border: 1px solid alpha(#{{text}}, 0.12);
}

#input {
    margin: 15px;
    padding: 12px;
    border: 1px solid alpha(#{{text}}, 0.1);
    border-radius: {{rounding}}px;
    background-color: alpha(#{{text}}, 0.05);
    color: #{{text}};
    font-weight: 600;
}

#outer-box { margin: 10px; border: none; background-color: transparent; }
#inner-box { margin: 10px; border: none; background-color: transparent; }
#scroll { margin: 0; border: none; }
#text { margin: 8px; border: none; color: #{{subtext}}; }
#entry { padding: 5px; border: none; border-radius: {{rounding}}px; }
#entry:selected { background-color: alpha(#{{accent}}, 0.2); border: none; }
#entry:selected #text { color: #{{text}}; font-weight: bold; }
