/* GENERATED by scripts/theme-switch ({{name}}). Do not edit. */
@define-color base     #{{base}};
@define-color mantle   #{{mantle}};
@define-color crust    #{{crust}};
@define-color surface0 #{{surface0}};
@define-color surface1 #{{surface1}};
@define-color overlay  #{{overlay}};
@define-color text     #{{text}};
@define-color subtext  #{{subtext}};
@define-color accent   #{{accent}};
@define-color accent2  #{{accent2}};
@define-color red      #{{red}};
@define-color orange   #{{orange}};
@define-color yellow   #{{yellow}};
@define-color green    #{{green}};
@define-color cyan     #{{cyan}};
@define-color blue     #{{blue}};
@define-color magenta  #{{magenta}};

* {
    font-family: "{{font_sans}}", "{{font_icon}}", "Adwaita Sans", sans-serif;
}
