/* GENERATED by scripts/theme-switch ({{name}}). Do not edit. Restart Firefox to apply. */
:root {
    --p-base: #{{base}};
    --p-mantle: #{{mantle}};
    --p-crust: #{{crust}};
    --p-surface0: #{{surface0}};
    --p-surface1: #{{surface1}};
    --p-overlay: #{{overlay}};
    --p-text: #{{text}};
    --p-subtext: #{{subtext}};
    --p-accent: #{{accent}};
    --p-accent2: #{{accent2}};
    --p-radius: {{rounding}}px;

    /* Window frame and toolbars */
    --lwt-accent-color: var(--p-crust) !important;
    --lwt-text-color: var(--p-text) !important;
    --toolbar-bgcolor: var(--p-base) !important;
    --toolbar-color: var(--p-text) !important;
    --toolbarbutton-icon-fill: var(--p-subtext) !important;
    --chrome-content-separator-color: var(--p-crust) !important;

    /* Tabs: the selected tab melts into the toolbar */
    --tab-selected-bgcolor: var(--p-base) !important;
    --tab-selected-textcolor: var(--p-text) !important;
    --tab-line-color: var(--p-accent) !important;
    --tab-loading-fill: var(--p-accent) !important;
    --tab-block-margin: 4px !important;

    /* Address bar */
    --toolbar-field-background-color: var(--p-surface0) !important;
    --toolbar-field-color: var(--p-text) !important;
    --toolbar-field-border-color: transparent !important;
    --toolbar-field-focus-background-color: var(--p-surface0) !important;
    --toolbar-field-focus-color: var(--p-text) !important;
    --toolbar-field-focus-border-color: var(--p-accent) !important;
    --urlbar-box-bgcolor: var(--p-surface0) !important;
    --urlbar-box-hover-bgcolor: var(--p-surface1) !important;
    --urlbar-box-active-bgcolor: var(--p-surface1) !important;
    --urlbar-box-focus-bgcolor: var(--p-surface0) !important;
    --urlbar-popup-url-color: var(--p-accent) !important;
    --autocomplete-popup-background: var(--p-surface0) !important;
    --autocomplete-popup-color: var(--p-text) !important;
    --autocomplete-popup-highlight-background: var(--p-surface1) !important;
    --autocomplete-popup-highlight-color: var(--p-text) !important;

    /* Menus, panels, sidebar */
    --arrowpanel-background: var(--p-surface0) !important;
    --arrowpanel-color: var(--p-text) !important;
    --arrowpanel-border-color: var(--p-surface1) !important;
    --arrowpanel-dimmed: var(--p-surface1) !important;
    --panel-background: var(--p-surface0) !important;
    --panel-color: var(--p-text) !important;
    --sidebar-background-color: var(--p-mantle) !important;
    --sidebar-text-color: var(--p-text) !important;
    --focus-outline-color: var(--p-accent) !important;
}

/* Shape follows the theme */
.tab-background { border-radius: var(--p-radius) !important; }
#urlbar-background, #searchbar { border-radius: var(--p-radius) !important; }
#urlbar[focused="true"] > #urlbar-background { box-shadow: 0 0 0 2px var(--p-accent) !important; }
.urlbarView-row[selected] > .urlbarView-row-inner { background-color: var(--p-surface1) !important; }
menupopup, panel { --panel-border-radius: var(--p-radius) !important; }
