/* GENERATED by scripts/theme-switch ({{name}}). Do not edit. Restart Firefox to apply. */
/* Firefox's own pages (new tab, about:*) and the blank page that flashes while loading */
@-moz-document url("about:newtab"), url("about:home"), url("about:blank"), url-prefix("about:preferences"), url-prefix("about:addons") {
    :root {
        --newtab-background-color: #{{base}} !important;
        --newtab-background-color-secondary: #{{surface0}} !important;
        --newtab-text-primary-color: #{{text}} !important;
        --newtab-text-secondary-color: #{{subtext}} !important;
        --newtab-primary-action-background: #{{accent}} !important;
        --in-content-page-background: #{{base}} !important;
        --in-content-page-color: #{{text}} !important;
        --in-content-box-background: #{{surface0}} !important;
        --in-content-primary-button-background: #{{accent}} !important;
        --in-content-primary-button-text-color: #{{base}} !important;
        --in-content-accent-color: #{{accent}} !important;
    }
    html, body { background-color: #{{base}} !important; }
}
