/* GENERATED by scripts/theme-switch ({{name}}). Do not edit. Restart Firefox to apply. */
:root {
    --p-base: #{{base}};
    --p-mantle: #{{mantle}};
    --p-crust: #{{crust}};
    --p-surface0: #{{surface0}};
    --p-surface1: #{{surface1}};
    --p-overlay: #{{overlay}};
    --p-text: #{{text}};
    --p-subtext: #{{subtext}};
    --p-accent: #{{accent}};
    --p-accent2: #{{accent2}};
    --p-radius: {{rounding}}px;

    /* Window frame and toolbars */
    --lwt-accent-color: var(--p-mantle) !important;   /* the strip behind the tabs: a notch darker than the toolbar */
    --lwt-text-color: var(--p-text) !important;
    --toolbar-bgcolor: var(--p-base) !important;
    --toolbar-color: var(--p-text) !important;
    --toolbarbutton-icon-fill: var(--p-subtext) !important;
    --chrome-content-separator-color: var(--p-crust) !important;

    /* Tabs: the selected tab melts into the toolbar */
    --tab-selected-bgcolor: var(--p-base) !important;
    --tab-selected-textcolor: var(--p-text) !important;
    --tab-line-color: var(--p-accent) !important;
    --tab-loading-fill: var(--p-accent) !important;
    --tab-block-margin: 4px !important;

    /* Address bar */
    --toolbar-field-background-color: var(--p-surface0) !important;
    --toolbar-field-color: var(--p-text) !important;
    --toolbar-field-border-color: transparent !important;
    --toolbar-field-focus-background-color: var(--p-surface0) !important;
    --toolbar-field-focus-color: var(--p-text) !important;
    --toolbar-field-focus-border-color: var(--p-accent) !important;
    --urlbar-box-bgcolor: var(--p-surface0) !important;
    --urlbar-box-hover-bgcolor: var(--p-surface1) !important;
    --urlbar-box-active-bgcolor: var(--p-surface1) !important;
    --urlbar-box-focus-bgcolor: var(--p-surface0) !important;
    --urlbar-popup-url-color: var(--p-accent) !important;
    --autocomplete-popup-background: var(--p-surface0) !important;
    --autocomplete-popup-color: var(--p-text) !important;
    --autocomplete-popup-highlight-background: var(--p-surface1) !important;
    --autocomplete-popup-highlight-color: var(--p-text) !important;

    /* Menus, panels, sidebar */
    --arrowpanel-background: var(--p-surface0) !important;
    --arrowpanel-color: var(--p-text) !important;
    --arrowpanel-border-color: var(--p-surface1) !important;
    --arrowpanel-dimmed: var(--p-surface1) !important;
    --panel-background: var(--p-surface0) !important;
    --panel-color: var(--p-text) !important;
    --sidebar-background-color: var(--p-mantle) !important;
    --sidebar-text-color: var(--p-text) !important;
    --focus-outline-color: var(--p-accent) !important;
}

/* ---- Shape and layout -------------------------------------------------------------- */
/* Tabs: floating pills. The selected one is a raised surface with a soft accent outline. */
:root { --tab-min-height: 34px !important; --tab-border-radius: var(--p-radius) !important; }
.tabbrowser-tab { padding-inline: 2px !important; }
.tab-background { margin-block: 3px !important; border: none !important; box-shadow: none !important;
    border-radius: var(--p-radius) !important; }
.tab-background[selected] { background-color: var(--p-surface0) !important;
    outline: 1px solid color-mix(in srgb, var(--p-accent) 50%, transparent) !important; outline-offset: -1px !important; }
.tabbrowser-tab:not([selected]):hover > .tab-stack > .tab-background {
    background-color: color-mix(in srgb, var(--p-surface0) 55%, transparent) !important; }
.tab-close-button { border-radius: 999px !important; }
.tab-label { font-weight: 500 !important; }

/* Toolbar: flat and compact, no separator lines */
#nav-bar { box-shadow: none !important; border: none !important; padding-block: 3px !important; }
#navigator-toolbox { border-bottom: none !important; }
#TabsToolbar { background-color: var(--p-mantle) !important; }
.toolbarbutton-1 { border-radius: var(--p-radius) !important; }
.toolbarbutton-1:hover { background-color: var(--p-surface0) !important; }

/* Address bar and suggestions */
#urlbar, #urlbar-input-container { --urlbar-height: 34px; }
#urlbar-background, #searchbar { border-radius: var(--p-radius) !important; border: none !important; }
#urlbar[focused="true"] > #urlbar-background { box-shadow: 0 0 0 2px var(--p-accent) !important; }
.urlbarView-row[selected] > .urlbarView-row-inner { background-color: var(--p-surface1) !important; }
.urlbarView-row-inner { border-radius: var(--p-radius) !important; }

/* Menus and panels */
menupopup, panel { --panel-border-radius: var(--p-radius) !important; }
menupopup { border-radius: var(--p-radius) !important; padding: 4px !important; }
menuitem, menu { border-radius: calc(var(--p-radius) - 2px) !important; margin-inline: 2px !important; }
menuitem[_moz-menuactive="true"], menu[_moz-menuactive="true"] { background-color: var(--p-surface1) !important; }
