/* GENERATED by scripts/theme-switch ({{name}}). Do not edit. */
* { font-family: "{{font_sans}}", "{{font_icon}}", "Adwaita Sans", sans-serif; font-size: 13px; }

.notification-row { outline: none; }
.notification-row:focus, .notification-row:hover { background: transparent; }

/* ── Notification cards (popups and inside the control center) ───────────────── */
.notification {
    background: rgba({{base_rgb}}, 0.94);
    border: 1px solid rgba({{text_rgb}}, 0.1);
    border-radius: {{rounding}}px;
    margin: 6px 8px;
    padding: 0;
}
.notification.critical { border-color: #{{red}}; }
.notification-content { background: transparent; padding: 10px 12px; }
.notification-default-action, .notification-action { background: transparent; border-radius: {{rounding}}px; color: #{{text}}; }
.notification-default-action:hover { background: rgba({{text_rgb}}, 0.06); }
.summary { color: #{{text}}; font-weight: 700; }
.time { color: #{{subtext}}; font-size: 11px; }
.body { color: #{{subtext}}; }
.close-button {
    background: rgba({{text_rgb}}, 0.1); color: #{{text}};
    border-radius: 999px; min-width: 20px; min-height: 20px; margin: 8px;
}
.close-button:hover { background: #{{red}}; color: #{{base}}; }
.notification-action { margin: 4px; padding: 6px; background: rgba({{text_rgb}}, 0.08); }
.notification-action:hover { background: rgba({{accent_rgb}}, 0.25); }
progressbar trough { background: rgba({{text_rgb}}, 0.15); border-radius: 999px; min-height: 6px; }
progressbar progress { background-image: linear-gradient(to right, #{{accent}}, #{{accent2}}); border-radius: 999px; min-height: 6px; }

/* ── Control center ──────────────────────────────────────────────────────────── */
.control-center {
    background: rgba({{base_rgb}}, 0.92);
    border: 1px solid rgba({{text_rgb}}, 0.1);
    border-radius: {{menu_radius}}px;
    padding: 6px;
}
.control-center-list { background: transparent; }
.control-center .notification-row .notification { background: rgba({{surface0_rgb}}, 0.7); }
.control-center-list-placeholder, .notification-group-headers { color: #{{overlay}}; }
.notification-group-icon { color: #{{overlay}}; }

.widget-title { margin: 10px 12px 4px; }
.widget-title > label { color: #{{text}}; font-size: 16px; font-weight: 700; }
.widget-title > button {
    background: rgba({{text_rgb}}, 0.08); color: #{{text}};
    border-radius: {{rounding}}px; padding: 4px 12px;
}
.widget-title > button:hover { background: rgba({{accent_rgb}}, 0.25); }

.widget-dnd { margin: 4px 12px; color: #{{subtext}}; }
.widget-dnd > switch { background: rgba({{text_rgb}}, 0.15); border-radius: 999px; }
.widget-dnd > switch:checked { background: #{{accent}}; }
.widget-dnd > switch slider { background: #{{text}}; border-radius: 999px; }

.widget-buttons-grid { margin: 6px 12px; padding: 0; background: transparent; }
.widget-buttons-grid > flowbox > flowboxchild > button {
    background: rgba({{surface0_rgb}}, 0.8); color: #{{text}};
    border-radius: {{rounding}}px; min-height: 40px; margin: 3px;
    transition: background 0.2s ease, color 0.2s ease;
}
.widget-buttons-grid > flowbox > flowboxchild > button:hover { background: rgba({{accent_rgb}}, 0.3); color: #{{accent}}; }
.widget-buttons-grid > flowbox > flowboxchild > button:active, .widget-buttons-grid > flowbox > flowboxchild > button:checked { background: #{{accent}}; color: #{{base}}; }

.widget-volume, .widget-backlight { margin: 4px 12px; padding: 8px 12px; background: rgba({{surface0_rgb}}, 0.8); border-radius: {{rounding}}px; color: #{{text}}; }
.widget-volume trough, .widget-backlight trough { background: rgba({{text_rgb}}, 0.18); border-radius: 999px; min-height: 6px; }
.widget-volume highlight, .widget-backlight highlight { background-image: linear-gradient(to right, #{{accent}}, #{{accent2}}); border-radius: 999px; }
.widget-volume slider, .widget-backlight slider { background: #{{text}}; border-radius: 999px; min-width: 14px; min-height: 14px; margin: -4px; }

.widget-mpris { margin: 4px 12px; padding: 8px; background: rgba({{surface0_rgb}}, 0.8); border-radius: {{rounding}}px; }
.widget-mpris-title { font-weight: 700; color: #{{text}}; }
.widget-mpris-subtitle { color: #{{subtext}}; }
.widget-mpris button { color: #{{text}}; border-radius: 999px; }
.widget-mpris button:hover { color: #{{accent}}; }
