/* GENERATED by scripts/theme-switch ({{name}}) from templates/waybar/style.css.tpl. Do not edit.
   Colours and font-family come from theme.css. */
@import "theme.css";

* {
    border: none;
    border-radius: 0;
    font-size: 13px;
    font-weight: 600;
    min-height: 0;
}

window#waybar { background: transparent; }

tooltip {
    background: alpha(@base, 0.94);
    border: 1px solid alpha(@text, 0.12);
    border-radius: {{rounding}}px;
}
tooltip label { color: @text; padding: 2px 4px; }

/* ── Islands ─────────────────────────────────────────── */
.modules-left, .modules-center, .modules-right {
    background-color: alpha(@base, 0.82);
    border: 1px solid alpha(@text, 0.08);
    border-radius: {{bar_radius}}px;
    padding: 0 6px;
}

#custom-layout, #clock, #network, #pulseaudio, #battery, #tray,
#bluetooth, #custom-vpn, #custom-activity, #custom-powerprofile, #custom-recorder, #custom-notifications, #custom-nightlight, #custom-power, #custom-sys, #cpu, #memory {
    padding: 0 9px;
    margin: 0;
    color: @text;
    transition: color 0.25s ease, background-color 0.25s ease;
}

/* ── Launcher ────────────────────────────────────────── */
#image.launcher {
    padding-left: 10px;
    padding-right: 8px;
    transition: opacity 0.25s ease;
}
#image.launcher:hover { opacity: 0.75; }

/* ── Workspaces: iOS page dots ───────────────────────── */
#workspaces { margin: 0 4px 0 0; }
#workspaces button {
    min-width: 7px;
    min-height: 7px;
    margin: 10px 3px;     /* keep (bar height - 2*margin) = dot size so the dots stay round */
    padding: 0;
    border-radius: 999px;
    background-color: alpha(@text, 0.28);
    transition: all 0.35s cubic-bezier(0.23, 1, 0.32, 1);
}
#workspaces button label { font-size: 0; min-height: 0; padding: 0; margin: 0; } /* empty label would force a tall button */
#workspaces button:hover { background-color: alpha(@text, 0.55); }
#workspaces button.active {
    min-width: 22px;
    background-color: @accent;
}
#workspaces button.urgent { background-color: @red; }

#custom-layout { color: @subtext; padding-left: 4px; }
#custom-layout:hover { color: @accent2; }

/* ── Clock ───────────────────────────────────────────── */
#clock { padding: 0 14px; letter-spacing: 0.3px; }

/* ── Right side ──────────────────────────────────────── */
#custom-sys { color: @subtext; }
#cpu, #memory { color: @subtext; font-weight: 500; }
#network      { color: @cyan; }
#pulseaudio   { color: @yellow; }
#pulseaudio.muted { color: @overlay; }
#battery      { color: @green; }
#battery.charging { color: @accent; }
#battery.warning:not(.charging)  { color: @orange; }
#battery.critical:not(.charging) { color: @red; animation: pulse 1s ease-in-out infinite alternate; }

#bluetooth { color: @accent; }
#bluetooth.off, #bluetooth.disabled { color: @overlay; }
#bluetooth.connected { color: @accent2; }
#custom-vpn.on { color: @green; }
#custom-vpn.idle { padding: 0; margin: 0; }
#custom-hubstatus { color: @accent; padding: 0 8px 0 0; font-size: 12px; }
#custom-hubstatus.mode { color: @green; }
#custom-hubstatus.idle { padding: 0; margin: 0; }
#custom-activity { color: @subtext; font-size: 17px; }
#custom-activity.busy { color: @orange; }
#custom-powerprofile.power-saver { color: @green; }
#custom-powerprofile.balanced { color: @subtext; }
#custom-powerprofile.performance { color: @orange; }
#custom-notifications.none { color: @overlay; }
#custom-notifications.notification { color: @accent; }
#custom-notifications.dnd-none, #custom-notifications.dnd-notification,
#custom-notifications.inhibited-none, #custom-notifications.inhibited-notification { color: @red; }
#custom-nightlight.off { color: @overlay; }
#custom-nightlight.on   { color: @orange; }

#custom-power { color: @subtext; padding-right: 11px; }
#custom-power:hover { color: @red; }
#bluetooth:hover, #custom-activity:hover, #custom-powerprofile:hover, #network:hover, #pulseaudio:hover,
#custom-notifications:hover, #custom-nightlight:hover { color: @accent2; }

#custom-recorder.recording { color: @red; animation: pulse 1s ease-in-out infinite alternate; }
#custom-recorder.idle { padding: 0; margin: 0; }

@keyframes pulse { to { opacity: 0.45; } }
