#!/usr/bin/env python3
"""Generate the Primo Plymouth boot splash from a theme palette.

Usage: gen-plymouth-theme.py [theme]      default: primo-dusk
Writes boot/plymouth/primo/{primo.plymouth, primo.script, logo.png, dot.png}. Pure standard library.
Install it with: sudo scripts/install-boot-splash.sh --apply
"""
import math
import struct
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
THEME = sys.argv[1] if len(sys.argv) > 1 else "primo-dusk"
OUT = ROOT / "boot" / "plymouth" / "primo"


def read_conf(path):
    data = {}
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            data[k.strip()] = v.split(" #")[0].strip()
    return data


def rgb(hexstr):
    return tuple(int(hexstr[i:i + 2], 16) for i in (0, 2, 4))


def png_rgba(path, w, h, pixel):
    rows = bytearray()
    for y in range(h):
        rows.append(0)
        for x in range(w):
            rows.extend(pixel(x, y))

    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body))

    path.write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0))
                     + chunk(b"IDAT", zlib.compress(bytes(rows), 9)) + chunk(b"IEND", b""))


def coverage(x, y, test, ss=4):
    """Anti-aliased coverage 0..1 of a shape by supersampling."""
    hit = 0
    for sy in range(ss):
        for sx in range(ss):
            hit += test(x + (sx + 0.5) / ss, y + (sy + 0.5) / ss)
    return hit / (ss * ss)


def main():
    p = read_conf(ROOT / "themes" / THEME / "theme.conf")
    a1, a2, base, crust = rgb(p["accent"]), rgb(p["accent2"]), rgb(p["base"]), rgb(p["crust"])
    OUT.mkdir(parents=True, exist_ok=True)

    # Logo: a ring with an accent -> accent2 gradient and a small dot at its centre
    size, cx, cy = 168, 84.0, 84.0

    def ring_px(x, y):
        def inside(px, py):
            d = math.hypot(px - cx, py - cy)
            return (60 <= d <= 76) or d <= 10
        a = coverage(x, y, inside)
        t = (x + y) / (2 * size)
        col = [round(a1[i] + (a2[i] - a1[i]) * t) for i in range(3)]
        return (*col, round(255 * a))

    png_rgba(OUT / "logo.png", size, size, ring_px)

    def dot_px(x, y):
        a = coverage(x, y, lambda px, py: math.hypot(px - 8, py - 8) <= 7)
        return (*a1, round(255 * a))

    png_rgba(OUT / "dot.png", 16, 16, dot_px)

    f = lambda c: f"{c / 255:.4f}"  # noqa: E731
    (OUT / "primo.script").write_text(f"""# Primo boot splash: gradient ring, three pulsing dots. Generated by scripts/gen-plymouth-theme.py ({THEME}).
Window.SetBackgroundTopColor({f(base[0])}, {f(base[1])}, {f(base[2])});
Window.SetBackgroundBottomColor({f(crust[0])}, {f(crust[1])}, {f(crust[2])});

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.x = Window.GetX() + Window.GetWidth() / 2 - logo.image.GetWidth() / 2;
logo.y = Window.GetY() + Window.GetHeight() / 2 - logo.image.GetHeight() / 2 - 40;
logo.sprite.SetPosition(logo.x, logo.y, 10);

dot.image = Image("dot.png");
dot1.sprite = Sprite(dot.image);
dot2.sprite = Sprite(dot.image);
dot3.sprite = Sprite(dot.image);
dots_y = logo.y + logo.image.GetHeight() + 48;
dots_x = Window.GetX() + Window.GetWidth() / 2 - dot.image.GetWidth() / 2;
dot1.sprite.SetPosition(dots_x - 28, dots_y, 10);
dot2.sprite.SetPosition(dots_x, dots_y, 10);
dot3.sprite.SetPosition(dots_x + 28, dots_y, 10);

frame = 0;
fun refresh_callback() {{
    frame++;
    dot1.sprite.SetOpacity(0.30 + 0.70 * ((Math.Sin(frame / 10.0) + 1) / 2));
    dot2.sprite.SetOpacity(0.30 + 0.70 * ((Math.Sin(frame / 10.0 - 0.9) + 1) / 2));
    dot3.sprite.SetOpacity(0.30 + 0.70 * ((Math.Sin(frame / 10.0 - 1.8) + 1) / 2));
}}
Plymouth.SetRefreshFunction(refresh_callback);
""")
    (OUT / "primo.plymouth").write_text("""[Plymouth Theme]
Name=Primo
Description=Gradient ring with pulsing dots
ModuleName=script

[script]
ImageDir=/usr/share/plymouth/themes/primo
ScriptFile=/usr/share/plymouth/themes/primo/primo.script
""")
    print(f"wrote {OUT.relative_to(ROOT)} from {THEME}")


if __name__ == "__main__":
    main()
