#!/usr/bin/env python3
"""Generate the Primo Plymouth boot splash from a theme palette.

Usage: gen-plymouth-theme.py [theme]      default: primo-dusk
Writes boot/plymouth/primo/{primo.plymouth, primo.script, logo.png, dot.png}. Pure standard library.
Install it with: sudo scripts/install-boot-splash.sh --apply
"""
import math
import struct
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
THEME = sys.argv[1] if len(sys.argv) > 1 else "primo-dusk"
OUT = ROOT / "boot" / "plymouth" / "primo"


def read_conf(path):
    data = {}
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            data[k.strip()] = v.split(" #")[0].strip()
    return data


def rgb(hexstr):
    return tuple(int(hexstr[i:i + 2], 16) for i in (0, 2, 4))


def png_rgba(path, w, h, pixel):
    rows = bytearray()
    for y in range(h):
        rows.append(0)
        for x in range(w):
            rows.extend(pixel(x, y))

    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body))

    path.write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0))
                     + chunk(b"IDAT", zlib.compress(bytes(rows), 9)) + chunk(b"IEND", b""))


def coverage(x, y, test, ss=4):
    """Anti-aliased coverage 0..1 of a shape by supersampling."""
    hit = 0
    for sy in range(ss):
        for sx in range(ss):
            hit += test(x + (sx + 0.5) / ss, y + (sy + 0.5) / ss)
    return hit / (ss * ss)


def main():
    p = read_conf(ROOT / "themes" / THEME / "theme.conf")
    a1, base, crust = rgb(p["accent"]), rgb(p["base"]), rgb(p["crust"])
    OUT.mkdir(parents=True, exist_ok=True)

    # Logo: the Primo mark (same shapes as templates/logo/*.svg.tpl), coloured like theme-switch does it
    mark = rgb(p.get("logo") or (p["accent"] if p["mode"] == "dark" else p["text"]))
    tile = rgb(p.get("logo_accent") or p["accent2"])
    scale, size = 3.5, 168   # the mark spans 48 units of its 64-unit grid: 48 * 3.5 = 168 px
    shapes = ((8, 8, 20, 48, (7, 7, 7, 7), mark), (34, 8, 22, 28, (6, 12, 12, 6), mark), (34, 42, 14, 14, (5, 5, 5, 5), tile))

    def in_shape(px, py, s):
        x, y, w, h, (tl, tr, br, bl), _ = s
        if not (x <= px <= x + w and y <= py <= y + h):
            return False
        for cx, cy, r, sx, sy in ((x + tl, y + tl, tl, -1, -1), (x + w - tr, y + tr, tr, 1, -1),
                                  (x + w - br, y + h - br, br, 1, 1), (x + bl, y + h - bl, bl, -1, 1)):
            if (px - cx) * sx > 0 and (py - cy) * sy > 0 and math.hypot(px - cx, py - cy) > r:
                return False   # outside a rounded corner
        return True

    def mark_px(x, y):
        for s in shapes:
            a = coverage(x, y, lambda px, py: in_shape(8 + px / scale, 8 + py / scale, s))
            if a:
                return (*s[5], round(255 * a))
        return (0, 0, 0, 0)

    png_rgba(OUT / "logo.png", size, size, mark_px)

    def dot_px(x, y):
        a = coverage(x, y, lambda px, py: math.hypot(px - 8, py - 8) <= 7)
        return (*a1, round(255 * a))

    png_rgba(OUT / "dot.png", 16, 16, dot_px)

    f = lambda c: f"{c / 255:.4f}"  # noqa: E731
    (OUT / "primo.script").write_text(f"""# Primo boot splash: the Primo mark, three pulsing dots. Generated by scripts/gen-plymouth-theme.py ({THEME}).
Window.SetBackgroundTopColor({f(base[0])}, {f(base[1])}, {f(base[2])});
Window.SetBackgroundBottomColor({f(crust[0])}, {f(crust[1])}, {f(crust[2])});

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.x = Window.GetX() + Window.GetWidth() / 2 - logo.image.GetWidth() / 2;
logo.y = Window.GetY() + Window.GetHeight() / 2 - logo.image.GetHeight() / 2 - 40;
logo.sprite.SetPosition(logo.x, logo.y, 10);

dot.image = Image("dot.png");
dot1.sprite = Sprite(dot.image);
dot2.sprite = Sprite(dot.image);
dot3.sprite = Sprite(dot.image);
dots_y = logo.y + logo.image.GetHeight() + 48;
dots_x = Window.GetX() + Window.GetWidth() / 2 - dot.image.GetWidth() / 2;
dot1.sprite.SetPosition(dots_x - 28, dots_y, 10);
dot2.sprite.SetPosition(dots_x, dots_y, 10);
dot3.sprite.SetPosition(dots_x + 28, dots_y, 10);

frame = 0;
fun refresh_callback() {{
    frame++;
    dot1.sprite.SetOpacity(0.30 + 0.70 * ((Math.Sin(frame / 10.0) + 1) / 2));
    dot2.sprite.SetOpacity(0.30 + 0.70 * ((Math.Sin(frame / 10.0 - 0.9) + 1) / 2));
    dot3.sprite.SetOpacity(0.30 + 0.70 * ((Math.Sin(frame / 10.0 - 1.8) + 1) / 2));
}}
Plymouth.SetRefreshFunction(refresh_callback);
""")
    (OUT / "primo.plymouth").write_text("""[Plymouth Theme]
Name=Primo
Description=The Primo mark with pulsing dots
ModuleName=script

[script]
ImageDir=/usr/share/plymouth/themes/primo
ScriptFile=/usr/share/plymouth/themes/primo/primo.script
""")
    print(f"wrote {OUT.relative_to(ROOT)} from {THEME}")


if __name__ == "__main__":
    main()
