# GENERATED by scripts/theme-switch ({{name}}). Do not edit.
# Sourced from ~/.bashrc by scripts/setup-shell.sh (remove it with `setup-shell.sh --remove`).
[[ $- == *i* ]] || return 0

# fzf: rounded border, palette colours
export FZF_DEFAULT_OPTS="--height=40% --layout=reverse --border=rounded --info=inline \
--prompt='❯ ' --pointer='▶' --marker='✓' \
--color=bg+:#{{surface0}},bg:#{{base}},fg:#{{text}},fg+:#{{text}},hl:#{{accent}},hl+:#{{accent}} \
--color=info:#{{subtext}},prompt:#{{accent}},pointer:#{{accent2}},marker:#{{green}},spinner:#{{accent2}},header:#{{accent}},border:#{{overlay}}"

# eza replaces ls when installed; bat colours follow the terminal palette
if command -v eza >/dev/null 2>&1; then
    alias ls='eza --icons=auto --group-directories-first'
    alias ll='eza -l --icons=auto --group-directories-first --git'
    alias la='eza -la --icons=auto --group-directories-first --git'
    alias lt='eza --tree --level=2 --icons=auto'
fi
export BAT_THEME="ansi"
command -v bat >/dev/null 2>&1 && export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# fzf key bindings (Ctrl+R history, Ctrl+T files, Alt+C directories) and completion
[[ -r /usr/share/fzf/key-bindings.bash ]] && source /usr/share/fzf/key-bindings.bash
[[ -r /usr/share/fzf/completion.bash ]] && source /usr/share/fzf/completion.bash

# zoxide: `z dir` jumps to frequent folders, `zi` picks interactively
command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init bash)"

# starship prompt (palette in ~/.config/starship.toml)
command -v starship >/dev/null 2>&1 && eval "$(starship init bash)"
