# GENERATED by scripts/theme-switch ({{name}}). Do not edit.
[General]
background={{login_bg}}
font={{font_sans}}
iconFont={{font_icon}}
base=#{{base}}
mantle=#{{mantle}}
surface=#{{surface0}}
text=#{{text}}
subtext=#{{subtext}}
accent=#{{accent}}
accent2=#{{accent2}}
red=#{{red}}
tint=#59{{base}}
# Pre-multiplied colours (#AARRGGBB) so the QML needs no colour maths
surfaceA=#bf{{surface0}}
surfaceB=#8c{{surface0}}
edge=#24ffffff
radius={{rounding}}
