# GENERATED by scripts/theme-switch ({{name}}). Do not edit.
[General]
background=background.png
font={{font_sans}}
iconFont={{font_icon}}
base=#{{base}}
mantle=#{{mantle}}
surface=#{{surface0}}
text=#{{text}}
subtext=#{{subtext}}
accent=#{{accent}}
accent2=#{{accent2}}
red=#{{red}}
tint=#59{{base}}
radius={{rounding}}
