# GENERATED by scripts/theme-switch ({{name}}). Do not edit.
[general]
early-exit = true
corner-roundness = {{rounding}}
initial-tool = "arrow"
copy-command = "wl-copy"
annotation-size-factor = 1.0
save-after-copy = false

[color-palette]
palette = ["#{{red}}", "#{{accent}}", "#{{yellow}}", "#{{green}}", "#{{accent2}}", "#{{text}}"]
