#!/usr/bin/env python3
"""Themed confirmation dialog.

Usage: confirm.py --title "Close terminal?" --text "..." --confirm "Close anyway" [--danger]
Exit status: 0 = confirmed, 1 = cancelled / closed / anything unexpected (the safe default).

Cancel has the keyboard focus, so a stray Enter never confirms. Escape cancels.
Colours and shape come from ~/.config/hypr/confirm.css (generated by scripts/theme-switch).
"""
import argparse
import os
import sys

import gi

gi.require_version("Gtk", "4.0")
gi.require_version("Gdk", "4.0")
from gi.repository import Gdk, Gtk  # noqa: E402

CSS_PATH = os.path.expanduser("~/.config/hypr/confirm.css")


def build_window(app, args, result):
    win = Gtk.ApplicationWindow(application=app)
    win.set_decorated(False)
    win.set_resizable(False)
    win.set_default_size(440, -1)
    win.add_css_class("primo-confirm")

    root = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=20)
    for side in ("top", "bottom", "start", "end"):
        getattr(root, f"set_margin_{side}")(24)

    header = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=16)
    icon = Gtk.Label(label=args.icon)
    icon.add_css_class("confirm-icon")
    if not args.danger:
        icon.add_css_class("info")
    icon.set_valign(Gtk.Align.START)
    icon.set_halign(Gtk.Align.CENTER)
    header.append(icon)

    col = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
    col.set_hexpand(True)
    title = Gtk.Label(label=args.title, xalign=0, wrap=True)
    title.add_css_class("confirm-title")
    col.append(title)
    if args.text:
        body = Gtk.Label(label=args.text, xalign=0, wrap=True, max_width_chars=44)
        body.add_css_class("confirm-text")
        col.append(body)
    header.append(col)
    root.append(header)

    buttons = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
    buttons.set_halign(Gtk.Align.END)
    cancel = Gtk.Button(label=args.cancel)
    ok = Gtk.Button(label=args.confirm)
    for b in (cancel, ok):
        b.add_css_class("confirm-btn")
    cancel.add_css_class("confirm-cancel")
    ok.add_css_class("confirm-ok")
    if args.danger:
        ok.add_css_class("danger")

    def finish(value):
        result["confirmed"] = value
        win.close()

    cancel.connect("clicked", lambda *_: finish(False))
    ok.connect("clicked", lambda *_: finish(True))
    buttons.append(cancel)
    buttons.append(ok)
    root.append(buttons)
    win.set_child(root)
    win.set_default_widget(cancel)

    keys = Gtk.EventControllerKey()
    keys.connect("key-pressed", lambda _c, keyval, *_: (finish(False), True)[1] if keyval == Gdk.KEY_Escape else False)
    win.add_controller(keys)
    win.connect("close-request", lambda *_: False)
    win.connect("map", lambda *_: cancel.grab_focus())
    return win, cancel, ok


def load_css():
    if not os.path.exists(CSS_PATH):
        return
    provider = Gtk.CssProvider()
    provider.load_from_path(CSS_PATH)
    Gtk.StyleContext.add_provider_for_display(
        Gdk.Display.get_default(), provider, Gtk.STYLE_PROVIDER_PRIORITY_USER)


def parse(argv):
    p = argparse.ArgumentParser()
    p.add_argument("--title", default="Are you sure?")
    p.add_argument("--text", default="")
    p.add_argument("--confirm", default="OK")
    p.add_argument("--cancel", default="Cancel")
    p.add_argument("--icon", default="")  # warning triangle (Nerd Font)
    p.add_argument("--danger", action="store_true", help="red confirm button")
    return p.parse_args(argv)


def main(argv=None):
    args = parse(argv if argv is not None else sys.argv[1:])
    result = {"confirmed": False}
    app = Gtk.Application(application_id="dev.primo.Confirm")

    def on_activate(application):
        load_css()
        win, _cancel, _ok = build_window(application, args, result)
        win.present()

    app.connect("activate", on_activate)
    app.run([sys.argv[0]])
    return 0 if result["confirmed"] else 1


if __name__ == "__main__":
    sys.exit(main())
