# GENERATED by scripts/theme-switch ({{name}}). Do not edit.
[global]
    font = {{font_sans}} 11
    frame_color = "#{{overlay}}"
    corner_radius = {{rounding}}
    highlight = "#{{accent}}, #{{accent2}}"   # gradient progress bar

[urgency_low]
    background = "#{{base}}ee"
    foreground = "#{{text}}"
    frame_color = "#{{surface1}}"

[urgency_normal]
    background = "#{{base}}ee"
    foreground = "#{{text}}"
    frame_color = "#{{accent}}"

[urgency_critical]
    background = "#{{red}}ee"
    foreground = "#{{crust}}"
    frame_color = "#{{red}}"
